name: production

on:
  push:
    branches: [master]
  workflow_dispatch

env:
  APP_NAME: spongiper
  REPO_NAME: Sniperbot
  REGISTRY: 192.168.2.10:5000
  DOCKER_HOST: tcp://192.168.2.100:2375

jobs:
  build:
    runs-on: [self-hosted]
    container:
      image: docker:cli
    outputs:
      version: ${{ steps.version.outputs.VERSION }}

    steps:
      - name: Install dependencies
        run: apk add --no-cache git

      - name: Clone repository
        env:
          USER: ${{ secrets.GIT_USER }}
          PASS: ${{ secrets.GIT_PASS }}
        run: git clone -b master https://$USER:$PASS@git.smplx.it/simplex/${{ env.REPO_NAME }}.git ./${{ env.REPO_NAME }}

      - name: Build and push Docker image
        if: github.event_name != 'pull_request'
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}
        run: |
          docker build -t ${{ env.APP_NAME }}:$VERSION ./${{ env.REPO_NAME }}
          docker tag ${{ env.APP_NAME }}:$VERSION ${{ env.REGISTRY }}/${{ env.APP_NAME }}:$VERSION
          docker tag ${{ env.APP_NAME }}:$VERSION ${{ env.REGISTRY }}/${{ env.APP_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.APP_NAME }}:$VERSION
          docker push ${{ env.REGISTRY }}/${{ env.APP_NAME }}:latest

  deploy:
    needs: build
    if: github.event_name != 'pull_request'
    runs-on: [self-hosted]
    container:
      image: docker:cli

    steps:
      - name: Remove existing container
        continue-on-error: true
        run: |
          docker stop ${{ env.APP_NAME }}
          docker rm ${{ env.APP_NAME }}

      - name: Deploy container
        env:
          TOKEN: ${{ secrets.TOKEN }}
          VERSION: ${{ needs.build.outputs.version }}
        run: |
          docker run -d \
            --name ${{ env.APP_NAME }} \
            --restart "unless-stopped" \
            --network bridge \
            -e TOKEN="$TOKEN" \
            -e DATABASE_NAME="${{ env.APP_NAME }}" \
            -e VERSION="$VERSION" \
            ${{ env.REGISTRY }}/${{ env.APP_NAME }}:$VERSION
